"""Add supplier and acquisition_date to inventory_changes

Revision ID: 6a03b89d815f
Revises: a7e231584c82
Create Date: 2025-03-01 21:18:17.916101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a03b89d815f'
down_revision = 'a7e231584c82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_changes', sa.Column('supplier', sa.String(), nullable=True))
    op.add_column('inventory_changes', sa.Column('acquisition_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_changes', 'acquisition_date')
    op.drop_column('inventory_changes', 'supplier')
    # ### end Alembic commands ### 