"""add_inventory_audit_table

Revision ID: a7e231584c82
Revises: 6e8c3bf71605
Create Date: 2025-02-27 15:31:38.758584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e231584c82'
down_revision = '6e8c3bf71605'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 